services:
  frankenphp:
    container_name: portfolio_app
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    ports:
      #- "80:8000" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mysql
    tty: false # comment this line in production, it allows to have nice human-readable logs in dev
    networks:
      - portfolio_network
  mysql:
    container_name: portfolio_db
    image: mysql:8.0
    ports:
      #- "3306:3306" # Only for local dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio_network
volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  portfolio_network:
    driver: bridge
