name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.TARGET_DIR }} || exit 1

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing/updating PHP dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader

            echo "Installing/updating Node.js dependencies..."
            npm install

            echo "Building frontend assets..."
            npm run build

            echo "Stopping containers gracefully..."
            docker compose -f docker-compose.prod.yml down

            echo "Building Docker images..."
            docker compose -f docker-compose.prod.yml build --no-cache

            echo "Starting services..."
            docker compose -f docker-compose.prod.yml up -d

            echo "Waiting for services to be ready..."
            sleep 10

            echo "Running database migrations..."
            docker compose -f docker-compose.prod.yml exec -T frankenphp php artisan migrate --force

            echo "Clearing and caching Laravel configurations..."
            docker compose -f docker-compose.prod.yml exec -T frankenphp php artisan optimize:clear
            docker compose -f docker-compose.prod.yml exec -T frankenphp php artisan optimize

            echo "Creating storage link..."
            docker compose -f docker-compose.prod.yml exec -T frankenphp php artisan storage:link

            echo "Deployment complete!"
