name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.TARGET_DIR }} || exit 1

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing/updating PHP dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader

            echo "Installing/updating Node.js dependencies..."
            npm install

            echo "Building frontend assets..."
            npm run build

            echo "Running database migrations..."
            php artisan migrate --force

            echo "Clearing and caching Laravel configurations..."
            php artisan optimize:clear
            php artisan optimize

            echo "Managing Docker Compose services..."
            docker compose restart

            echo "Deployment complete!"
